# Generated by Django 2.2.7 on 2020-02-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_part',
            old_name='articles',
            new_name='blogs',
        ),
        migrations.RenameField(
            model_name='about_part',
            old_name='awards',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='about_part',
            old_name='projects',
            new_name='courses',
        ),
    ]
